### ISSUE TITLE
helm faces

### ISSUE THREAD

**Issue by StreakyCobra** [cryon/subatomic#13]
Thanks a lot for this theme :smile: I use it through [Spacemacs](https://github.com/syl20bnr/spacemacs) which does an heavy usage of [`helm`](https://github.com/emacs-helm/helm). As far as I saw, there is no specific support for `helm` in your theme, and I'm not really a big fan of its colouring (mainly the green background for selection and blue background for title):

![helm](https://i.imgur.com/4PpJ6bY.png)

It would be nice to make `helm` more coherent with your theme. I will not propose a PR as I'm not used to theming, nor I am really good at mixing colours :-)

**Comment by cryon** [comment]
Thanks for reporting, and providing a screenshot (which helps a lot)! I'm not a helm user myself but I definitely want to support it (and I totally agree that it doesn't look good in your screenshot). I will put that on my todo-list! With a little luck I can take a look at in in the weekend.

**Comment by StreakyCobra** [comment]
> but I definitely want to support it

Really nice of you!

> and I totally agree that it doesn't look good in your screenshot

My tastes are not so wrong then :smile: 

Thanks for your support!

**Comment by StreakyCobra** [comment]
Up :innocent:

**Comment by cryon** [comment]
Wow... I totally forgot about this issue! :sob: 
I have made an initial attempt to make helm look more consistent with the rest of the theme. It will be released together with a few tweaks and a new customizable variable to make comment delimiters more visible.

The new version will be on MELPA tonight! I'll will keep this issue open a while and encourage you to report any weirdness you might find regarding helm in it!

**Comment by StreakyCobra** [comment]
:+1: Really nice of you! I'll test it and report "weirdness" if any :-)

**Comment by StreakyCobra** [comment]
I've found one improvement that can be done :-) See the difference between the default spacemacs theme:

![spacemacs-dark](https://i.imgur.com/9fkcXhs.png)

and subatomic:

![spacemacs-dark](https://i.imgur.com/Xk3z78S.png)

The highlighted letters, in this case `u` and `i` aren't highlighted on the selected line.

Some references that may be useful:

- [This post](https://github.com/syl20bnr/spacemacs/issues/4540#issuecomment-172889500) explaining this (I hope at least) for `ivy` (a package similar to helm)
- [The spacemacs themes](https://github.com/nashamri/spacemacs-theme)

**Comment by cryon** [comment]
Good find! I thought it might be impossible to fix it bacause helm was setting the line-highlight color after the "match item" color. But your screenshot proves me wrong! 

Thanks for the references, I think the spacemacs theme is especially useful to take a look at!

Hopefully I can have this fixed relatively soon!

**Comment by StreakyCobra** [comment]
:+1: Thanks for your help!

**Comment by cryon** [comment]
The problem actually turned out to be what i wrote in my previous comment. The selected line font face is applied after the highlighted item (the matched letters) so I can't use the same property if I want to be able to distinguish them.

I "solved" it by not using the green background for the matched item, and not fiddeling with the foreground color on the selected line. It works, but I think it can be a bit difficult to see which line is selected.

I plan to do a bit of tweaking in the future to make selections more coherent over the whole theme.

Anyhow, version 1.8.1 will be out on melpa in a coupe of hours.

**Comment by StreakyCobra** [comment]
Ok, I'll try it later tonight and give a feedback.

We are now two spacemacs developers to use your theme (justbur and me), so we can try to help you to support more faces. For instance we just started to use [`hydra`](https://github.com/abo-abo/hydra), and there are 5 faces for which colors could probably be improved.

Do you prefer if I try to find some existing colors to put on those faces and I PR the changes, or do you prefer if I just report them and you do the job yourself to have a consistent theme? (I'm not sure to be good at coloring ;-) )

Second question, I have a few faces that I changed because they are not optimal from my point of view, like `font-lock-comment-delimiter-face` and `hl-line` because they are hard to see by default. Are you open for this kind of changes if I PR it? If not it's not a problem I keep this in my own config :-)

**Comment by cryon** [comment]
Pull requests are always welcome! When it comes to additional support for modes I'll accept pretty much anything as long as the code is somewhat clean and the commits are logical and follows the principle of one commit per feature and/or fix. If some font faces turns out weird it can be patched later so it's not really a big deal.

When it comes to changing existing colors I might have some opinions so an issue with a screenshot or two would be great followed by a PR if it seems like a good change.

As an example when you mention both `font-lock-comment-delimiter-face` and `hl-line`, I personally prefer them to be very suble. I have, however, recieved a few remarks regarding the `font-lock-comment-delimiter-face` font face so I decided to add a customizable variable for that which can be accessed through `M-x customize-group RET subatomic`. I am not against adding a variable to increase the contrast of the `hl-line`.

**Comment by StreakyCobra** [comment]
> Pull requests are always welcome! When it comes to additional support for modes I'll accept pretty much anything as long as the code is somewhat clean and the commits are logical and follows the principle of one commit per feature and/or fix. If some font faces turns out weird it can be patched later so it's not really a big deal.

:+1:

> When it comes to changing existing colors I might have some opinions so an issue with a screenshot or two would be great followed by a PR if it seems like a good change.

:+1:

> As an example when you mention both font-lock-comment-delimiter-face and hl-line, I personally prefer them to be very subtle. I have, however, received a few remarks regarding the font-lock-comment-delimiter-face so I decided to add a customizable variable for that which can be accessed through M-x customize-group RET subatomic. I am not against adding another variable to increase the contrast of the hl-line.

Nah, it's fine, probably a personal preference and we have a theming layer in spacemacs that allows users to easily modify themes.
